### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ekaj2** [johnroper100/CrowdMaster#18]
I noticed that CrowdMaster is missing the standard GPL 3 licensing block at the head of all of the script files. Would you like me to add these?

**Comment by johnroper100** [comment]
Ok, if you want.

**Comment by johnroper100** [comment]
Can you make it copyright the _CrowdMaster Developer Team_?

**Comment by ekaj2** [comment]
Sure.

**Comment by ekaj2** [comment]
Finished: please see pull request.

**Comment by ekaj2** [comment]
Sorry, I thought you had said _Development_ not _Developer_ :-|

**Comment by ekaj2** [comment]
Finished: please see pull request.
