### ISSUE TITLE
Nodes: More than one input being connected to same socket

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#26]
In the Agent Generation node editor you can connect the output of more than one node to the input of another node (see image attached). Seems to break Blender convention of one input per socket and may lead to unexpected outcomes for users.

Suggested behavior is when an new input is connected to a socket with an existing input, the existing input is deleted and replaced with the new input (in line with the compositor).

Simulation node editor has not been tested for same behavior but suggest that it should also conform to a single input into a socket.

![20170613 - more than one node connected](https://user-images.githubusercontent.com/3905694/27054849-ca468f3a-5005-11e7-8c9d-137db22f48ef.PNG)

**Comment by johnroper100** [comment]
In both the generation and simulation systems, the input of multiple nodes per socket is needed. In the generation node tree, multiple inputs to the generate node act as multiple placement setups.

**Comment by johnroper100** [comment]
In the simulation node tree, multiple inputs are needed to pass the required data to each node. In fact, some nodes even have controls to decide what to do with each input (http://crowdmaster.org/docs/simulation/nodes/output/output.html).

@Peter-Noble can talk more about this.
