### ISSUE TITLE
Agent Generation is not being added to Undo stack

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#27]
IF you generate agents and then use Undo (Ctrl+Z) then it undoes the operation prior to Agent Generation. for the relevant view.

To repeat:
Step 1 - create a simple Generation noodle.

Step 2 - do some form of operation and view the history (F3 in 3D view). Example: Resize the cube 

![image](https://user-images.githubusercontent.com/3905694/27153132-9d85596a-5193-11e7-83dd-1bfc6e23c08a.png)

Step 3 - Generate Agents and view change history - Agent generation is not part of the History. 

![image](https://user-images.githubusercontent.com/3905694/27153160-b72259f4-5193-11e7-915c-5e0fd0b6e252.png)

Step 4 - Undo and it will undo generation AND the previous operator resulting in the cube reverting to previous size.

![image](https://user-images.githubusercontent.com/3905694/27153192-cde8e9e6-5193-11e7-8b36-6a3f0f88be86.png)

I understand that you can regenerate the agent system by hitting Agent Gen again. However, it is natural for people to use Undo which may lead to unexpected results and unhappy users.

**Comment by johnroper100** [comment]
Ok, this has been fixed in b56efc0e3f471412a70e20fd1facbd338e3cc1b8
