### ISSUE TITLE
Multiple node trees datablocks and multiple file saves, open and closes causes deletion of node tree datablocks without warning 

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#30]
Background: Most datablocks will be not be saved if there are no users linked (see here: https://docs.blender.org/manual/en/dev/data_system/data_blocks.html). 

Crowdmaster node tree datablocks with a User Count of 0 are not written on save and purged on exiting a Blender session effectively deleting them forever like most other data blocks. Note there is a previous issue raised that unlinking a datablock does not reduce the user count for _that session only_ and so may still be saved (#29).

Issue: If you create multiple Sim and/or Gen datablocks they will all save because of issue #29 even if unlinked. When you close and reload the file only the Sim or Gen datablock(s) displayed will **_not_** have a User count of 0. Any node trees you load into the node editor will also be updated and not have a 0 next to their name in the nodetree browser list. Any unloaded node trees will have a 0 next to their name in the node tree browser list from the datablock and **_will not be saved and are purged on exit_** 💥 😱

Steps to recreate:
Step 1: Create two Sim node trees and two Gen node trees. In the node tree browser list they will _not_ have 0 next to their name. Leave one of the node trees displayed (I have used Brain 2 in this example) and save file. Exit blender. 

![image](https://user-images.githubusercontent.com/3905694/27249377-597f846e-5357-11e7-9789-4812d72dca49.png)

![image](https://user-images.githubusercontent.com/3905694/27249385-88b2615c-5357-11e7-8118-c097190350a9.png)

Step 2: Reopen blender file. In the node tree browser list the displayed node tree will _not_ have 0 next to it's name. All the other Sim and Gen node trees will have 0 next to their name. Save file and exit Blender.

![image](https://user-images.githubusercontent.com/3905694/27249404-222b6e32-5358-11e7-9071-bd1f278c03e7.png)

![image](https://user-images.githubusercontent.com/3905694/27249407-319c4e7c-5358-11e7-88ad-237484560e77.png)

Step 3: Reopen file. Displayed node tree will remain - **_all other node trees will have been deleted_**

![image](https://user-images.githubusercontent.com/3905694/27249415-85c63d5a-5358-11e7-8505-e5a827a55b79.png)

![image](https://user-images.githubusercontent.com/3905694/27249423-9bfdc4bc-5358-11e7-91d4-fdce21e39af2.png)

Step 4: Hope you have a backup!!!  😰

**Comment by Peter-Noble** [comment]
"Solved" by automatically setting the fake user on newly created node trees when the file is saved.
