### ISSUE TITLE
Add to Group Node does not assign agents to created group

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#31]
Current behavior: Add to Group node creates a Crowdmaster Group - but does not assign agents to the group (count is 0 after generation).

Expected behavior: Generated agents are assigned to Group.

Steps to reproduce:
Step 1 - create Gen node like the one in image. Press Generate Agents. Note the three positions indicated with a ˅ have been tried and all resulted in no agents being assigned to a group.

Note: Have tried adding multiple objects and multiple templates in case a group had to have more than one object/template. Have also tried saving, exiting and reloading in case it is a refreshing issue. In both cases error still occurs.

![image](https://user-images.githubusercontent.com/3905694/27255802-3c7d0610-53e9-11e7-8c2a-17219dc21bbd.png)

Crowdmaster 1.2.1
Windows 10
Blender 2.78b

**Comment by Peter-Noble** [comment]
All fixed!
