### ISSUE TITLE
Positioning Not working

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/CrowdMaster#5]
Even without random rotation the agents objects do not move into their random locations as they should.

The generation code can be found in https://github.com/johnroper100/CrowdMaster/blob/master/cm_agent_generation/generation.py

**Comment by Peter-Noble** [comment]
See latest commit. The wrong function was returning {'FINISHED'}.

**Comment by johnroper100** [comment]
Thanks!

**Comment by johnroper100** [comment]
Positioning still does not work

**Comment by johnroper100** [comment]
Fixed it! Now moving on to issue https://github.com/johnroper100/CrowdMaster/issues/4.
