### ISSUE TITLE
Saving Sim on frame other than frame one causes agents to start future sims from saved frame position

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#52]
Current behavior: After generating a sim if you move the current frame to any frame other than frame 1 and save the file when you generate the sim again it returns the current frame 1 but the agents start from where they were on saved frame. This necessitates a "regen" of the agents to get them back to their starting position, which if generated randomly cannot be identical to what you had before...

Note 1: I am assuming this is not an undocumented "feature" allowing you to set the start point of your sim.

Note 2: Cannot test if this also occurs with frozen agent groups due to issue #31 

Expected behavior: Agents always start from frame 1 in their original position.

Steps to reproduce

Step 1: generate agents
![image](https://user-images.githubusercontent.com/3905694/27352826-6bc76d80-5645-11e7-811d-5eca541a37d6.png)

Step 2: run sim to at least frame 100. Does not seem to matter if you interrupt the sim part way through or let it run all the way to the end.

Step 3: Move to frame 100 and save file
![image](https://user-images.githubusercontent.com/3905694/27352974-dcb273fa-5645-11e7-9333-1162422dd8e3.png)

Step 4: Regenerate Simulation - agents start in Frame 100 position.
![image](https://user-images.githubusercontent.com/3905694/27353037-09357738-5646-11e7-9066-e57ef0b1734b.png)

**Comment by johnroper100** [comment]
Moved to asana
