### ISSUE TITLE
Python error if bone in Pose or Edit mode when Resetting group

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#54]
Current behavior: If you have a agent that is child object of a bone, when resetting the group if you have either the agent bone or the originating bone in Pose mode it will generate a python error. The group cannot be reset. Same error occurs if bone in Edit mode.

Expected behavior: Group is reset as if both bones are in Object mode.

Steps to repeat:
Step 1: Set up a noodle as in the image below. Armature and Mesh are *not grouped or parented*. Set up an empty as the agent generation target.

![image](https://user-images.githubusercontent.com/3905694/27610436-a17133a8-5bd1-11e7-9a0d-f02cca5d9a9a.png)

Step 2: Generate agent
![image](https://user-images.githubusercontent.com/3905694/27610451-b50eb21e-5bd1-11e7-8b42-5e8a0e660571.png)

Step 3: Change originating armature into Pose mode
![image](https://user-images.githubusercontent.com/3905694/27610533-0f7fea9c-5bd2-11e7-9905-3fec63a98daa.png)

Step 4: Select group in tool panel (if not selected). Reset group from Tools panel. Python error will appear. Group, armature and mesh remain.

![image](https://user-images.githubusercontent.com/3905694/27610581-44342118-5bd2-11e7-895d-c650e868454c.png)

Step 5: Select the Agent armature bone and change to Pose mode.
![image](https://user-images.githubusercontent.com/3905694/27610642-8ca1a664-5bd2-11e7-87bb-aca82292e084.png)

Step 6: Select group in tool panel (if not selected). Reset group from Tools panel. Python error will appear. Group, armature and mesh remain.

![image](https://user-images.githubusercontent.com/3905694/27610689-bcf695ae-5bd2-11e7-98b2-aeb79c4714f9.png)

To repeat for Edit mode same instruction, replace Pose mode with Edit mode.

**Comment by johnroper100** [comment]
Fixed!
