### ISSUE TITLE
Generating a new set of agents reset previously generated agents resulting no more than one group of agents at a time

### ISSUE THREAD

**Issue by axb2035** [johnroper100/CrowdMaster#55]
Current behavior: When one set of auto agents is generated it resets the previously auto generated agents meaning you can only have one set of auto generated agents at a time.

Expected behavior: Only the agents for the Generated group generated, no other groups are reset.

Note 1: Added manual agent group and had it selected in the View Group Details panel when generating second group. No change in behavior.

Note 2: you can workaround this issue by combining the nodes together into one. 
![image](https://user-images.githubusercontent.com/3905694/27660043-01ecde22-5c99-11e7-9917-41f6f10a0e23.png)

Steps to repeat: 
Step 1: Open sample file.
[groups overwriting.zip](https://github.com/johnroper100/CrowdMaster/files/1110154/groups.overwriting.zip)

Step 2: Select Gen - Cube noodle for agent generation. Generate Agents. Cube will appear and Cube brain group will be listed in the View Group Details panel list.

![image](https://user-images.githubusercontent.com/3905694/27659312-57042512-5c96-11e7-87e4-6d8ec96904a5.png)

Step 3: Select Gen - Sphere noodle for agent generation. Generate Agents. Cube agent previously generated will be deleted along with Cube brain group. Sphere will appear and Sphere brain group will be listed in the View Group Details panel list.

![image](https://user-images.githubusercontent.com/3905694/27659375-967fc6ec-5c96-11e7-91cd-4d8b173fff6f.png)

Step 4: Select Gen - Cube noodle for agent generation again. Generate Agents. Now Sphere agent previously generated will be deleted along with Sphere brain group. Cube will appear and Cube brain group will be listed in the View Group Details panel list.

![image](https://user-images.githubusercontent.com/3905694/27659449-d5ad5960-5c96-11e7-892e-b304124808a3.png)

**Comment by Peter-Noble** [comment]
Now that groups are working again could you have a play with those and see if it solved this problem @axb2035 ?

**Comment by johnroper100** [comment]
Confirmed, looking at this

**Comment by johnroper100** [comment]
@Peter-Noble In this examples, both node tress generate with a gr
![capture](https://user-images.githubusercontent.com/9782943/27802617-eb20a1bc-5ff2-11e7-9d48-a38a74328ae4.JPG)
oup name of `cm`

**Comment by Peter-Noble** [comment]
That's new in the develop branch as part of the work to support better automatic grouping. "cm" is the equivalent to what used to be "cm_allAgents". You can stop groups of agents from being regenerated by hitting this:
![selection_072](https://user-images.githubusercontent.com/5630018/27804027-a8de50e2-6024-11e7-9a05-87258946418c.png)

**Comment by Peter-Noble** [comment]
The defaults for manual groups have been changed so you can't accidentally delete all your manual agents.  This resetting of groups is the intended behavior. A scene will normally have a single generation graph and so all agents will be generated by a single graph. Used like this it then makes more sense that all groups are reset by default. If you like how a group is set out and don't want it removed you can hit "Freeze Placement".
