### ISSUE TITLE
Agent Generation and Simulation node tree missing on restart

### ISSUE THREAD

**Issue by scnncs** [johnroper100/CrowdMaster#56]
Behaviour: Agent Generation and Simulation node tree are saved, the file closed. Upon reopening both node trees are missing in the dropdown and have to be remade.

Anyone else experiencing this? Thx.

**Comment by Peter-Noble** [comment]
Which version are you using? In 1.3.0 it should automatically set a fake user when you save the file.

**Comment by scnncs** [comment]
Blender 2.78 + CrowdMaster 1.2.1
I renamed the node tree's in all instances. Not sure if this matters.

**Comment by Peter-Noble** [comment]
ok, this is a know issue with 1.2.1. I suggest upgrading to 1.3.0. https://github.com/johnroper100/CrowdMaster/releases/tag/1.3.0

**Comment by scnncs** [comment]
oh great, i had missed that update. thanks a lot for the fast answer.

**Comment by Peter-Noble** [comment]
No problem :)
