### ISSUE TITLE
Cannot install addon

### ISSUE THREAD

**Issue by crcrcrcnf** [johnroper100/CrowdMaster#57]
When the CrowdMaster folder is dropped into the addons folder in Blender program files, the addon shows up in the user interface, but it gives an error when trying to enable it.

**Comment by johnroper100** [comment]
What error do you get? Also, what version of the add-on are you using?

**Comment by crcrcrcnf** [comment]
The error message is attached. I am using the "latest version" of CrowdMaster, from the download button here:
http://crowdmaster.org/download.html.
I am using Blender version 2.78c.


![delete later](https://user-images.githubusercontent.com/30665466/28886253-cf483a3a-7786-11e7-8428-c075709c792e.png)

**Comment by TheDuckCow** [comment]
@crcrcrcnf hello, it looks like a permission issue with one of the setup configurations trying to create a subdirectory. Can you please give it a test by running blender as an administrator? usually not necessary, but I want to see if that resolves the issue for this case.

**Comment by crcrcrcnf** [comment]
Yes, as admin it is fine. I will close the issue. Thank you!

**Comment by TheDuckCow** [comment]
One followup question - after enabling it once as an administrator, does it work enabling it thereafter in future non-administrator blender sessions?

**Comment by crcrcrcnf** [comment]
Yes, as a matter of fact. I found that interesting. Works now even in normal sessions.
