### ISSUE TITLE
evacuation modeling?

### ISSUE THREAD

**Issue by mimooh** [johnroper100/CrowdMaster#58]
Hi, I am looking for a tool which would evacuate hundreds of agents from a multi-storey buildings. Is your tool capable of that?

**Comment by axb2035** [comment]
Hi Mimooh,

Crowdmaster is primarily and a tool for artistic expression. It is not designed to simulate "real-world" evacuation models for buildings and vehicles for design and regulatory requirements.

So if you are looking at from an artistic purpose then yes, you could do this with Crowdmaster, though it may be challenging as your first project as you learn the tool.

Hope this helps!

    - andrew

**Comment by mimooh** [comment]
Hi Andrew. But how do you avoid collisions of dynamic objects? Do you
use RVO2 or such?

-- 
Karol Kreński
tel. 517-302-055

**Comment by axb2035** [comment]
Hi Mimooh,

Crowdmaster has no pre-programmed models of behavior (what is called a  "brain" in Crowdmaster) for the agents. You can build the agents to behave however you want. Clearly a zombie will behave differently from a beetle or a panicking human.

    - andrew

**Comment by mimooh** [comment]
OK, seems like a valuable project, but not exactly for what I need.
Thanks anyway!

-- 
Karol Kreński
tel. 517-302-055

**Comment by axb2035** [comment]
OK - good luck with your project!
