### ISSUE TITLE
Fixed position formations

### ISSUE THREAD

**Issue by Peter-Noble** [johnroper100/CrowdMaster#7]
Please see my folk and pull request for relevant updates.

Agents can now request specific positions in formations (by index number of the vertex in the guide mesh) but to make this useful each agent needs to request a different position. I think an option would be to have the generation script assign a vertex index to each agent as an agent variable (a dictionary called agvars stored in each agent object for things like this. At the end of each frame the resulting variables in agvars are moved to access to be used) based on where the script places the agent. The attached file demonstrates how it might be used. The input string would look something like: Formation.A.fixedDist(State.userObject.vars["targetID"]). I don't really understand how the generation script is working so I can't finish formation for the moment.

[FixedPositionFormations.zip](https://github.com/johnroper100/CrowdMaster/files/391574/FixedPositionFormations.zip)

**Comment by johnroper100** [comment]
Currently in https://github.com/johnroper100/CrowdMaster/blob/master/cm_agent_generation/generation.py all the generation code is stored. You can see in this issue https://github.com/johnroper100/CrowdMaster/issues/5 that with the merge the agent vexation has stopped working. I am working on this. If you have any ideas about the error message it would be great.
Currently, all the generator does is duplicate the agent group and set a random location, rotation, and scale (neither work, see the issue).

**Comment by johnroper100** [comment]
I want to try to get the add-on to a state where it is easy to understand by any user, but still (hopefully) get to a point where it has the power of MASSIVE. For one, I have updating the description of each node. Currently, many are the same and this is confusing to say the least.

**Comment by johnroper100** [comment]
So for now, my first goal is just to get the random agent generation working and have the agents added to the agent list automatically. After that, I am going to work on agent generation in a row/array like an army and we can try to apply the positions to your positional code.

**Comment by johnroper100** [comment]
https://upload.wikimedia.org/wikipedia/commons/c/cf/Christlarena2.jpg

This is the type of scene I would like to create.

**Comment by johnroper100** [comment]
Here is the test crowd scene:
[test-crowd-scene.zip](https://github.com/johnroper100/CrowdMaster/files/392060/test-crowd-scene.zip)

Here is a gif of the problem. You can follow the steps in your own file.
![2016-07-30_15-26-50](https://cloud.githubusercontent.com/assets/9782943/17272657/46995c48-566a-11e6-99b4-52bf460392ba.gif)

**Comment by johnroper100** [comment]
Also, I would like it if the node tree could be greatly simplified for this sort of thing. I wish it could be as simple as 2-5 nodes. Take a look at [these MASSIVE videos](https://www.youtube.com/watch?v=J_XnLifS0Ng) to see how the node trees are set up there.

**Comment by Peter-Noble** [comment]
Sounds good. If you could get the generator so that it's fairly easy to set up a stadium that would be amazing! Can I suggest that we create another issue or a wiki page for gathering ideas for simplifying and performance issues?

**Comment by johnroper100** [comment]
Yes. The page is https://github.com/johnroper100/CrowdMaster/wiki/Ideas-about-performance-and-simplification

**Comment by johnroper100** [comment]
After looking at some examples, I see how the formation mesh is used.

**Comment by johnroper100** [comment]
Now how can I setup a mesh whenever a formation of agents is generated my my code?

**Comment by Peter-Noble** [comment]
Maybe we could just write a function which creates a new node tree for the formation controller and then in the generation code make a mesh by adding vertices at the same positions as the agents.

**Comment by johnroper100** [comment]
That could work

**Comment by johnroper100** [comment]
@Peter-Noble look at these formations: https://www.youtube.com/watch?v=CkLoZCuy1Rw&app=desktop

**Comment by Peter-Noble** [comment]
So to do it like that we could add another field to the generator which is a guide object and then agents are generated wherever there is a vertex in the guide object. Then assign an agent variable equal to the index of the vertex they were assigned at and use shape keys to change the shape of the mesh. If we did that we wouldn't be too far off what Miarmy can do and it would be easy to add another option to the generator when the formation type is set to shape.

**Comment by Peter-Noble** [comment]
This isn't really an issue anymore but a feature request. I've broken down the feature request into tasks in the "Quick Projects" section.
