### ISSUE TITLE
Mingle sim not working

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/CrowdMaster#8]
I recreated the mingle scene from Inaite with CrowdMaster nodes. I have not changed any of the node code and I kept all the values exactly the same, but when I ran the sim, each object got three keyframes right at the beginning of the animation the stopped. I will attach a file when I have a chance.

**Comment by Peter-Noble** [comment]
If you could upload that example that would be great!

**Comment by johnroper100** [comment]
No, I forgot. I will send the file.
